theme: jekyll-theme-cayman
title: Conway's Game of Life Simulation
author: Stephen Zq
description: To create a simulation of Conway’s Game of Life using C++. Built hierarchical functions for structure design, using Simple and Fast Multimedia Library to load media assets efficiently.
